name = "SimpleChecksums"
uuid = "99b673fe-21e3-4c03-9f5c-4e20ec304e65"
authors = ["Phil Killewald <reallyasi9@users.noreply.github.com> and contributors"]
version = "1.0.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2"
julia = "1.6"

[extras]
Libz = "2ec943e9-cfe8-584d-b93d-64dcb6d567b7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "Libz"]
